### ISSUE TITLE
MVP Review - Auth

### ISSUE THREAD

**Issue by mmcnulty20** [Arsoni5t/Webfilms#4]
- [x] Missing/Broken Splash page components
- [x] Change text on splash and sign up form to reflect that email isn't entered on the splash
- [x] Splash page needs a footer
- [ ] Footer should not have dead links ( links that don't lead anywhere, or text that seems like it _should_ be a link, but doesn't lead anywhere ). Instead, come up with some filler text, or shrink the size of the footer. You can do this later.
- [ ] Less vertical space between rows of text in the footer (other than the top one with your phone number)
- [x] Need Demo User - add a button to splash, and perhaps the sign up blue button should be a demo button instead :)

**Comment by bradlarsoncode** [comment]
- Blue button now a link to enter as a demo user. I must say I'm proud how quickly I was able to figure out how to do that. 

- Text on splash have been updated to reflect email isn't entered on splash.

- I aesthetically like the splash as it in regards to buttons, so if you are okay with it, I'd prefer demo login access be on the sign up and sign in pages exclusively. 

- I cannot seem to get the space between the footer lines any closer. I've tried for half an hour.

**Comment by bradlarsoncode** [comment]
- Also, can't figure out what's happening with the bottom of the splash page. Will need to meet up.

**Comment by mmcnulty20** [comment]
- [x] Clear errors after leaving a page (going from sign in to sign up or vice versa, errors will persist)
- [x] Some space between TV image on splash and text

While the other two checkboxes will need to be addressed later, I'll mark this as complete once these are done :)
